/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.diplomado.pucmm.mescyt.java.gui.campos.formatos;

import java.awt.Color;
import java.text.NumberFormat;

/**
 *
 * @author ecabrerar
 */
public class CalculadoraPrestamo extends javax.swing.JDialog {

    //Campos con valores iniciales
    private double vlrMonto = 100000;
    private double vlrTasa = 7.0;  //7.5%
    private int numTiempo = 5;
    private double cuotaMensual;

    //Formats to format and parse numbers
    private NumberFormat formatoMonto;
    private NumberFormat formatoTasa;
    private NumberFormat formatoCuotaMensual;

    /**
     * Creates new form CalculadoraPrestamo
     *
     * @param parent
     * @param modal
     */
    public CalculadoraPrestamo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        inicializarFormatos();
        cuotaMensual = calcularMontoCuota(vlrMonto, vlrTasa, numTiempo);
        initComponents();
    }

    private void inicializarFormatos() {
        formatoMonto = NumberFormat.getNumberInstance();
        formatoTasa = NumberFormat.getNumberInstance();
        formatoTasa.setMinimumFractionDigits(3);//Cantidad de digitos con punto decimal minimo

        formatoCuotaMensual = NumberFormat.getCurrencyInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCabecera = new javax.swing.JLabel();
        lblMonto = new javax.swing.JLabel();
        txtVlrMonto = new javax.swing.JFormattedTextField(formatoMonto);
        lblTasa = new javax.swing.JLabel();
        txtVlrTasa = new javax.swing.JFormattedTextField(formatoTasa);
        lblCuotaMensual = new javax.swing.JLabel();
        lblTiempo = new javax.swing.JLabel();
        txtNumTiempo = new javax.swing.JFormattedTextField();
        txtVlrCuotaMensual = new javax.swing.JFormattedTextField(formatoCuotaMensual);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblCabecera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCabecera.setText("Calculadora de Préstamos");
        lblCabecera.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblMonto.setText("Monto :");

        txtVlrMonto.setValue(vlrMonto);
        txtVlrMonto.setColumns(10);
        txtVlrMonto.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtVlrMontoPropertyChange(evt);
            }
        });

        lblTasa.setText("Tasa:");

        txtVlrTasa.setValue(vlrTasa);
        txtVlrTasa.setColumns(10);
        txtVlrTasa.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtVlrTasaPropertyChange(evt);
            }
        });

        lblCuotaMensual.setText("Cuota Mensual: ");

        lblTiempo.setText("Tiempo:");

        txtNumTiempo.setValue(numTiempo);
        txtNumTiempo.setColumns(10);
        txtNumTiempo.setToolTipText(" Tiempo (Años)");
        txtNumTiempo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtNumTiempoPropertyChange(evt);
            }
        });

        txtVlrCuotaMensual.setColumns(10);
        txtVlrCuotaMensual.setValue(cuotaMensual);
        txtVlrCuotaMensual.setEditable(false);
        txtVlrCuotaMensual.setForeground(Color.red);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCabecera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMonto)
                                    .addComponent(lblTasa)
                                    .addComponent(lblTiempo))
                                .addGap(56, 56, 56)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtVlrTasa, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNumTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVlrMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCuotaMensual)
                                .addGap(1, 1, 1)
                                .addComponent(txtVlrCuotaMensual, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMonto)
                    .addComponent(txtVlrMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVlrTasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTasa))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTiempo)
                    .addComponent(txtNumTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCuotaMensual)
                    .addComponent(txtVlrCuotaMensual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtVlrMontoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtVlrMontoPropertyChange
        // TODO add your handling code here:

        vlrMonto = ((Number) txtVlrMonto.getValue()).doubleValue();

        cuotaMensual = calcularMontoCuota(vlrMonto, vlrTasa, numTiempo);
        txtVlrCuotaMensual.setValue(cuotaMensual);
    }//GEN-LAST:event_txtVlrMontoPropertyChange

    private void txtVlrTasaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtVlrTasaPropertyChange
        // TODO add your handling code here:
        vlrTasa = ((Number) txtVlrTasa.getValue()).doubleValue();

        cuotaMensual = calcularMontoCuota(vlrMonto, vlrTasa, numTiempo);
        txtVlrCuotaMensual.setValue(cuotaMensual);

    }//GEN-LAST:event_txtVlrTasaPropertyChange

    private void txtNumTiempoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtNumTiempoPropertyChange
        // TODO add your handling code here:

        numTiempo = ((Number) txtNumTiempo.getValue()).intValue();

        cuotaMensual = calcularMontoCuota(vlrMonto, vlrTasa, numTiempo);
        txtVlrCuotaMensual.setValue(cuotaMensual);
    }//GEN-LAST:event_txtNumTiempoPropertyChange

    private double calcularMontoCuota(double monto, double tasa, int numTiempo) {

        double tasaMensual;
        double parcial;
        double denominador;

        numTiempo *= 12;   //numeros de meses
        if (tasa > 0.01) {
            tasaMensual = tasa / 100.0 / 12.0; //tasa mensual  a partir de la tasa anual
            parcial = Math.pow((1 + tasaMensual), (0.0 - numTiempo));
            denominador = (1 - parcial) / tasaMensual;
        } else { //tasa ~= 0
            denominador = numTiempo;
        }

        return (-1 * monto) / denominador;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            CalculadoraPrestamo dialog = new CalculadoraPrestamo(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCabecera;
    private javax.swing.JLabel lblCuotaMensual;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblTasa;
    private javax.swing.JLabel lblTiempo;
    private javax.swing.JFormattedTextField txtNumTiempo;
    private javax.swing.JFormattedTextField txtVlrCuotaMensual;
    private javax.swing.JFormattedTextField txtVlrMonto;
    private javax.swing.JFormattedTextField txtVlrTasa;
    // End of variables declaration//GEN-END:variables
}
