/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.diplomado.pucmm.mescyt.javase.swing;

import java.awt.GridLayout;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.diplomado.pucmm.mescyt.javase.utilidades.UtilPantalla;

/**
 *
 * @author ecabrerar
 */
public class CalculadoraPrespuesto extends javax.swing.JDialog {

    private final int vlrMontoPresupuestado = 0;
    private double vlrGastoFijo = 0.0;
    private final List<Double> gastosFijos = new ArrayList<>();

    private NumberFormat formatoMontoPresupuestado;
    private NumberFormat formatoGastoFijo;

    private NumberFormat formatoMoneda;

    /**
     * Creates new form CalculadoraPrespuesto
     */
    public CalculadoraPrespuesto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        inicializarFormatos();

        initComponents();

        UtilPantalla pantalla = new UtilPantalla(this);
        pantalla.centrar();

    }

    private void inicializarFormatos() {
        formatoMontoPresupuestado = NumberFormat.getNumberInstance();

        formatoGastoFijo = NumberFormat.getNumberInstance();
        formatoGastoFijo.setMinimumFractionDigits(3);//Cantidad de digitos con punto decimal minimo

        formatoMoneda = NumberFormat.getCurrencyInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        txtVlrGastoFijos = new javax.swing.JFormattedTextField(formatoGastoFijo);
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMontoPresupuestado = new javax.swing.JFormattedTextField(formatoMontoPresupuestado);
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Gastos Fijos"));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Energía Eléctrica", "Agua", "Alimentación", "Transporte", "Combustible", "Internet", "Teléfono y/o Móvil", " ", " " }));

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtVlrGastoFijos.setColumns(10);
        txtVlrGastoFijos.setValue(vlrGastoFijo);
        txtVlrGastoFijos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtVlrGastoFijosFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtVlrGastoFijos, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(txtVlrGastoFijos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CalculadoraPrespuesto");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Monto :");

        txtMontoPresupuestado.setColumns(10);
        txtMontoPresupuestado.setValue(vlrMontoPresupuestado);
        txtMontoPresupuestado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMontoPresupuestadoFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMontoPresupuestado, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMontoPresupuestado, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton2.setText("Calcular");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(29, 29, 29))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        vlrGastoFijo = ((Number) txtVlrGastoFijos.getValue()).doubleValue();

        if (vlrGastoFijo > 0) {
            gastosFijos.add(vlrGastoFijo);
        }

        txtVlrGastoFijos.setValue(new Double(0));

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        double sumatoriaGastosFijos = sumarGastosFijos();
        int montoPresupuestado = ((Number) txtMontoPresupuestado.getValue()).intValue();      

        generarMensaje(montoPresupuestado,sumatoriaGastosFijos);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtMontoPresupuestadoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMontoPresupuestadoFocusGained
       
        txtMontoPresupuestado.setValue(null);
    }//GEN-LAST:event_txtMontoPresupuestadoFocusGained

    private void txtVlrGastoFijosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVlrGastoFijosFocusGained
        
        txtVlrGastoFijos.setValue(null);
    }//GEN-LAST:event_txtVlrGastoFijosFocusGained

    public void generarMensaje(double montoPresupuestado,double sumatoriaGastosFijos) {
        
        double balance = montoPresupuestado - sumatoriaGastosFijos;
          
        if (balance < 0) {        
            
            JPanel panel = getPanelMensaje(String.format("Ha excedido lo presupuestado por %s pesos", formatoMoneda.format(balance)),
                                            balance,
                                            montoPresupuestado,
                                            sumatoriaGastosFijos);
            
            mensajeConIconoAlerta(panel,JOptionPane.ERROR_MESSAGE);

        } else if (balance > 0) {

                  JPanel panel = getPanelMensaje(String.format("Todavía está dentro de lo presupuestado, puedes gastar %s pesos", formatoMoneda.format(balance)),
                                            balance,
                                            montoPresupuestado,
                                            sumatoriaGastosFijos);
            
            mensajeConIconoAlerta(panel, JOptionPane.WARNING_MESSAGE);

        } else if (balance == 0) {
            JPanel panel = getPanelMensaje("Gastaste exactamente lo presupuestado",
                                            balance,
                                            montoPresupuestado,
                                            sumatoriaGastosFijos);
            
            mensajeConIconoAlerta(panel, JOptionPane.INFORMATION_MESSAGE);

        }

    }

    private void mensajeConIconoAlerta(JPanel panelMensaje, int tipo) { 
        
        JOptionPane.showMessageDialog(this, panelMensaje , "Mensaje del Sistema", tipo);
    }

    private double sumarGastosFijos() {
        //Sumar todos los valores usando Java 8
        return gastosFijos
                .stream()
                .filter((Double t) -> t > 0)
                .mapToDouble((Double t) -> t)
                .sum();
    }
    
    private JPanel getPanelMensaje(String mensaje,double balance,double montoPresupuestado,double sumatoriaGastosFijos){
        
        JLabel labelMensaje = new JLabel(mensaje);
        
        JLabel labelPresupuestado = new JLabel(String.format("Monto Prespuestado: %s", formatoMoneda.format(montoPresupuestado)));
        
        JLabel labelGastosFijos = new JLabel(String.format("Gastos Fijos: %s", formatoMoneda.format(sumatoriaGastosFijos)));
        
        JLabel labelBalance = new JLabel(String.format("Balance: %s", formatoMoneda.format(balance)));
         
        JPanel panel = new JPanel(new GridLayout(0,1));
        
        panel.add(labelMensaje);
        panel.add(labelPresupuestado);
        panel.add(labelGastosFijos);
         panel.add(labelBalance);
        
        return panel;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraPrespuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraPrespuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraPrespuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraPrespuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            CalculadoraPrespuesto dialog = new CalculadoraPrespuesto(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JFormattedTextField txtMontoPresupuestado;
    private javax.swing.JFormattedTextField txtVlrGastoFijos;
    // End of variables declaration//GEN-END:variables
}
